version: "3.1"

services:
  db:
    image: mysql:5.7		
    environment:
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaiuser
      MYSQL_ROOT_PASSWORD: arryaws123
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
      update_config: 
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: always
    networks:
      - int_net
  pma:
    image: phpmyadmin/phpmyadmin:4.8.3
    links:
      - db:mysql
    ports:
      - '8080:80'
    deploy:
      restart_policy:
        condition: always
      update_config:
        parallelism: 2
        delay: 10s
    healthcheck:
      test: curl -f http://localhost/ || exit 1
      timeout: 3s
      interval: 30s
    networks:
      - proxy_net
      - int_net
  web:
    image: arryws/finalproject-kuasai-advanced:web-1.0
    links:
      - db:mysql
    deploy:
      restart_policy:
        condition: always
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      - proxy_net
      - int_net
  proxy:
    image: arryws/finalproject-kuasai-advanced:proxy-1.0
    ports:
      - '80:80'
    depends_on:
      - web
      - pma
    deploy:
      replicas: 3
      restart_policy:
        condition: always
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      - proxy_net
      - ext_net

volumes:
  mysql-data:

networks:
  int_net:
    driver: overlay
  proxy_net:
    driver: overlay
  ext_net:
    driver: overlay	

