version: '3.1'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
      MYSQL_ROOT_PASSWORD: examplerootpw
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - int_net
  pma:
    image: phpmyadmin/phpmyadmin:4.8.5
    depends_on:
      - db
    healthcheck:
      test: curl -f http://localhost/ || exit 1
      timeout: 3s
      interval: 30s
    networks:
    - proxy_net
    - int_net
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - db
    networks:
      - proxy_net
      - int_net
  proxy:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    depends_on:
      - db
    ports:
      - '80:80'
    networks:
      - ext_net
      - proxy_net
volumes:
  mysql-data:
networks:
  int_net:
    driver: bridge
  proxy_net:
    driver: bridge
  ext_net:
    driver: bridge

